/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.JView;

import br.com.loja.dao.ProdutoDao;
import br.com.loja.entidade.Produto;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author higor
 */
public class AlterarProdutoJFrame extends javax.swing.JFrame {
    
    private Produto p = null;

    /**
     * Creates new form NewJFrame
     */
    public AlterarProdutoJFrame(Produto p) {
        this.p = p;
        initComponents();
        
        if (p != null) {
            jTextField2.setText(p.getCod() + "");
            jTextField1.setText(p.getTipo());
            CorTextFlied.setText(p.getCor());
            jdia.setText(p.getDataEntrada());
            jmes1.setText(p.getDataEntrada());            
            jano.setText(p.getDataEntrada());
            ValorTextFlied.setText(p.getValor());
            FornecedorTextFlied.setText(p.getFornecedor());
            QtdTextFlied.setText(p.getQtd());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jdia = new javax.swing.JTextField();
        jmes1 = new javax.swing.JTextField();
        jano = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        CorTextFlied = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ValorTextFlied = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        QtdTextFlied = new javax.swing.JTextField();
        FornecedorTextFlied = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incensação de Produto");
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(500, 180));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 430, 30));

        jLabel2.setText("Código:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, -1));

        jLabel4.setText("Data de Entrada: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(jdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 30, -1));

        jmes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmes1ActionPerformed(evt);
            }
        });
        getContentPane().add(jmes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 30, -1));
        getContentPane().add(jano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 50, -1));

        jLabel24.setText("/");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 10, -1));

        jLabel25.setText("/");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 10, -1));

        CorTextFlied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorTextFliedActionPerformed(evt);
            }
        });
        getContentPane().add(CorTextFlied, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 100, -1));

        jLabel5.setText("Cor: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        ValorTextFlied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTextFliedActionPerformed(evt);
            }
        });
        getContentPane().add(ValorTextFlied, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 90, -1));

        jLabel6.setText("Valor: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel7.setText("Fornecedor: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel8.setText("Quantidade:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        QtdTextFlied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QtdTextFliedActionPerformed(evt);
            }
        });
        getContentPane().add(QtdTextFlied, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 60, -1));

        FornecedorTextFlied.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorTextFliedActionPerformed(evt);
            }
        });
        getContentPane().add(FornecedorTextFlied, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(jTextField2.getText());
        String tipo = jTextField1.getText();
        
        String cor = CorTextFlied.getText();
        
        String DataEntrada = jdia.getText() + "/" + jmes1.getText() + "/" + jano.getText();
        
        String valor = ValorTextFlied.getText();
        
        String fornecedor = FornecedorTextFlied.getText();
        
        String qtd = QtdTextFlied.getText();
        
        Produto p = new Produto();
        
        p.setCod(cod);
        p.setTipo(tipo);
        p.setCor(cor);
        p.setDataEntrada(DataEntrada);
        p.setValor(valor);
        p.setFornecedor(fornecedor);
        p.setQtd(qtd);
        
        try {
            
            ProdutoDao pDao = new ProdutoDao();
            pDao.alterar(p);
            
            JOptionPane.showMessageDialog(this, "Produto Alterado!");
            
        } catch (SQLException ex) {
            String msg = "Erro ao alterar produto :";
            msg = msg + ex.getMessage();
            JOptionPane.showMessageDialog(this, msg);
        }
        
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jmes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmes1ActionPerformed

    private void CorTextFliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorTextFliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorTextFliedActionPerformed

    private void ValorTextFliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTextFliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTextFliedActionPerformed

    private void QtdTextFliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QtdTextFliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QtdTextFliedActionPerformed

    private void FornecedorTextFliedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorTextFliedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FornecedorTextFliedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarProdutoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarProdutoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarProdutoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarProdutoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarProdutoJFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CorTextFlied;
    private javax.swing.JTextField FornecedorTextFlied;
    private javax.swing.JTextField QtdTextFlied;
    private javax.swing.JTextField ValorTextFlied;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jano;
    private javax.swing.JTextField jdia;
    private javax.swing.JTextField jmes1;
    // End of variables declaration//GEN-END:variables
}
