/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.loja.JView;

import br.com.loja.dao.ProdutoDao;
import br.com.loja.entidade.Produto;
import br.com.loja.view.Telas.EstoqueLoja;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author higor
 */
public class JFrameMenuProduto extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameMenuProduto
     */
    public JFrameMenuProduto() throws SQLException {
        initComponents();

        ProdutoDao dao = new ProdutoDao();
        List<Produto> pList = dao.consultatodos();

        preencherTable(pList);

    }

    private void preencherTable(List<Produto> pList) {
        String[] cabecalho = new String[]{"Código", "Nome", "Cor", "DataEntrada", 
            "Valor", "Fornecedor", "Quantidade"};

        String[][] conteudo = new String[pList.size()][7];
        for (int i = 0; i < pList.size(); i++) {
            Produto p = pList.get(i);
            conteudo[i][0] = p.getCod() + "";
            conteudo[i][1] = p.getTipo();
            conteudo[i][2] = p.getCor();
            conteudo[i][3] = p.getDataEntrada();
            conteudo[i][4] = p.getValor();
            conteudo[i][5] = p.getFornecedor();
            conteudo[i][6] = p.getQtd();
        }
        TabelaP.setModel(new javax.swing.table.DefaultTableModel(
                conteudo,
                cabecalho));

        JAlterar.setEnabled(false);
        JExcluir.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JAlterar = new javax.swing.JButton();
        JExcluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("                            Produtos");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabelaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaP);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setText("+");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(0, 153, 153));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel2.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37))
        );

        JAlterar.setBackground(new java.awt.Color(0, 153, 153));
        JAlterar.setText("Alterar");
        JAlterar.setEnabled(false);
        JAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlterarActionPerformed(evt);
                Alterar(evt);
            }
        });

        JExcluir.setBackground(new java.awt.Color(255, 51, 51));
        JExcluir.setText("Excluir");
        JExcluir.setEnabled(false);
        JExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JExcluirActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Estoque da loja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(85, 85, 85)
                        .addComponent(JAlterar)
                        .addGap(163, 163, 163)
                        .addComponent(JExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JAlterar)
                            .addComponent(JExcluir))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Inserir 
        Jprodutoinserir frame = new Jprodutoinserir();
        frame.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void JAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlterarActionPerformed
        // TODO add your handling code here:
        // String codStr = JOptionPane.showInputDialog("Informe o código do produto!");
        //int cod = 0;

        // if (codStr == null) {
        //     return;
        // }
//
        //  try {
        //      cod = Integer.parseInt(codStr);
//  } catch (Exception e) {
        //          JOptionPane.showMessageDialog(this, "O código informado não é um número válido!");
        //          return;
        //      }
//
        //      ProdutoDao dao = new ProdutoDao();
        //      Produto p = null;
        //      try {
        //          p = dao.consultarporcod(cod);
        //      } catch (SQLException ex) {
        //          JOptionPane.showMessageDialog(this, "Falha ao consultar!" + ex.getMessage());
        //          return;
        //      }
        //      if (p != null) {
        //          AlterarProdutoJFrame frame = new AlterarProdutoJFrame(p);
        //          frame.setVisible(true);
//
        //      } else {
        //          JOptionPane.showMessageDialog(this, "O código informado não corresponde a um produto!");
//
        //     }
    }//GEN-LAST:event_JAlterarActionPerformed

    private void JExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JExcluirActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() == 10) {

            try {
                String nome = jTextField1.getText();

                ProdutoDao dao = new ProdutoDao();
                List<Produto> pList = dao.consultarPorNome(nome);
                preencherTable(pList);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao consultar cliente no banco:- " + ex.getMessage());
            }
        }

    }//GEN-LAST:event_jTextField1KeyReleased

    private void TabelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPMouseClicked
        // TODO add your handling code here:
        JAlterar.setEnabled(true);
        JExcluir.setEnabled(true);
    }//GEN-LAST:event_TabelaPMouseClicked

    private void Alterar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar
        // TODO add your handling code here:
        //pega a linha selecionada
        int linha = TabelaP.getSelectedRow();
        
        //Pega o modelo que tem todos os dados da tabela
        TableModel model = TabelaP.getModel();
        
        
        String codstr = model.getValueAt(linha, 0).toString();
        int cod = Integer.parseInt(codstr);
        ProdutoDao pDao = new ProdutoDao();
        Produto p = null;
        try {
            p = pDao.consultarporcod(cod);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar cliente (cod-'" +cod+ "') no banco.-"  
                    +ex.getMessage());
            return;
        }
        if (p!=null){
            AlterarProdutoJFrame frame = new AlterarProdutoJFrame(p);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_Alterar

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EstoqueLoja frame = null;
        try {
            frame = new EstoqueLoja();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMenuProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameMenuProduto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFrameMenuProduto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAlterar;
    private javax.swing.JButton JExcluir;
    private javax.swing.JTable TabelaP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
